version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    commit-message:
      prefix: 'fix:'
      prefix-development: 'chore:'
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
        update-types:
          - 'minor'
          - 'patch'
      development-dependencies:
        dependency-type: 'development'
        exclude-patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
      reliability-kit:
        patterns:
          - '@dotcom-reliability-kit/*'
        update-types:
          - 'minor'
          - 'patch'
