parameters:
  executor:
    default: default
    type: executor

executor: << parameters.executor >>

steps:
  - attach-workspace
  - doppler-circleci/install
  - doppler-circleci/load_secrets
  - run:
      name: Run the project build-production task
      command: npx dotcom-tool-kit build:ci
  - persist-workspace:
      path: .
