parameters:
  node-version:
    default: '16.14'
    type: string

executor:
  name: node/default
  tag: <<parameters.node-version>>

steps:
  - attach-workspace
  - run:
      name: Run the project build-production task
      command: npx dotcom-tool-kit build:ci
  - persist-workspace:
      path: .
