export const automatedComment = '# CONFIG GENERATED BY DOTCOM-TOOL-KIT, DO NOT EDIT BY HAND\n'

export type JobConfig = {
  context?: string | string[]
  requires?: string[]
  filters?: { branches?: { only?: string; ignore?: string }; tags?: { only?: string } }
}

type TriggerConfig = {
  schedule?: { cron: string; filters?: { branches: { only?: string; ignore?: string } } }
}

export type Job = string | { [job: string]: JobConfig }

export type Trigger = string | { [trigger: string]: TriggerConfig }

export type Workflow = {
  jobs?: Job[]
  triggers?: Trigger[]
}

export interface CircleConfig {
  version: number
  orbs: { [orb: string]: string }
  workflows?: {
    version: number
    [workflow: string]: Workflow | number
  }
}
