export const automatedComment = '# CONFIG GENERATED BY DOTCOM-TOOL-KIT, DO NOT EDIT BY HAND\n'

export type JobConfig = {
  type?: string
  docker?: { image: string; environment?: Record<string, string> }[]
  context?: string | string[]
  requires?: string[]
  filters?: { branches?: { only?: string; ignore?: string }; tags?: { only?: string } }
  executor?: string
}

type TriggerConfig = {
  schedule?: { cron: string; filters?: { branches: { only?: string; ignore?: string } } }
}

export type Job = string | { [job: string]: JobConfig }

export type Trigger = string | { [trigger: string]: TriggerConfig }

export type Workflow = {
  jobs?: Job[]
  triggers?: Trigger[]
}

export interface CircleConfig {
  version: 2.1
  orbs: {
    [orb: string]: string
  }
  executors: {
    [executor: string]: {
      docker: { image: string }[]
    }
  }
  jobs: {
    [job: string]: {
      docker: { image: string }[]
      steps: (string | { [command: string]: { path?: string } })[]
    }
  }
  workflows: {
    'tool-kit': {
      when: {
        not: {
          equal: ['scheduled_pipeline', '<< pipeline.trigger_source >>']
        }
      }
      jobs: Job[]
    }
    nightly: {
      when: {
        and: [
          {
            equal: ['scheduled_pipeline', '<< pipeline.trigger_source >>']
          },
          {
            equal: ['nightly', '<< pipeline.schedule.name >>']
          }
        ]
      }
      jobs: Job[]
    }
  }
}
