export const automatedComment = '# CONFIG GENERATED BY DOTCOM-TOOL-KIT, DO NOT EDIT BY HAND\n'

export type JobConfig = {
    context?: string | string[]
    requires?: string[]
    filters?: { branches?: { only?: string; ignore?: string }, tags?: { only?: string} }
}

export type ComputedJob = {
    'node-version': string,
} & JobConfig

type TriggerConfig = {
    schedule?: { cron: string; filters?: { branches: { only?: string; ignore?: string } } }
}

export type Workflow = {
    jobs?: (string | { [job: string]: JobConfig })[]
    triggers?: (string | { [trigger: string]: TriggerConfig })[]
}

export interface CircleConfig {
    version: number
    orbs: { [orb: string]: string }
    workflows?: {
      version: number
      [workflow: string]: Workflow | number
    }
}