plugins:
  - "@dotcom-tool-kit/webpack"
  - "@dotcom-tool-kit/babel"

not-lifecycles:
  "build:local":
    - "webpack:development"
    - "babel:development"
  "build:ci":
    - "webpack:production"
    - "babel:production"
  "build:deploy":
    - "webpack:production"
    - "babel:production"
