plugins:
  - '@dotcom-tool-kit/webpack'
  - '@dotcom-tool-kit/babel'

hooks:
  'build:local':
    - WebpackDevelopment
    - BabelDevelopment
  'build:ci':
    - WebpackProduction
    - BabelProduction
  'build:remote':
    - WebpackProduction
    - BabelProduction
