plugins:
  - '@dotcom-tool-kit/webpack'
  - '@dotcom-tool-kit/babel'

lifecycles:
  'build:local':
    - 'webpack:development'
    - 'babel:development'
  'build:ci':
    - 'webpack:production'
    - 'babel:production'
  'build:remote':
    - 'webpack:production'
    - 'babel:production'
