import { z } from 'zod'

export const ParallelSchema = z.object({
  tasks: z.array(z.record(z.record(z.unknown())))
}).describe(`Run Tool Kit tasks in parallel

### Task options

\`tasks\`: an array listing the tasks to run in parallel, and the options to run each task with. Each element in the array is an object with a single key and value; the key is the name of the task to run, and the value is the options object for that task. Other tasks' options are documented in their plugin's readme.

#### Example

~~~yaml
commands:
  run:local:
    - Parallel:
        tasks:
          - Node:
              entry: server/index.js
          - Webpack:
              watch: true
~~~

<!-- hide autogenerated schema docs -->
`)

export type ParallelOptions = z.infer<typeof ParallelSchema>

export const Schema = ParallelSchema
