plugins:
  - '@dotcom-tool-kit/frontend-app'
  - '@dotcom-tool-kit/nodemon'
  - '@dotcom-tool-kit/next-router'
  - '@dotcom-tool-kit/prettier'
  - '@dotcom-tool-kit/lint-staged-npm'
  - '@dotcom-tool-kit/jest'
  - '@dotcom-tool-kit/circleci-npm'
  - '@dotcom-tool-kit/secret-squirrel'

hooks:
  run:local:
    - Nodemon
    - NextRouter
  git:precommit:
    - SecretSquirrel
    - LintStaged

options:
  '@dotcom-tool-kit/vault':
    team: next
    app: next-static # for testing
  '@dotcom-tool-kit/next-router':
    appName: static # for testing
  '@dotcom-tool-kit/lint-staged-npm':
    formatGlob: index.js
  '@dotcom-tool-kit/jest':
    configPath: 'jest.config.js'
