plugins:
  - "@dotcom-tool-kit/frontend-app"
  - "@dotcom-tool-kit/heroku-postbuild"
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/mocha"
  - "@dotcom-tool-kit/n-test"

options:
  "@dotcom-tool-kit/eslint":
    files:
      - webpack.config.js
  "@dotcom-tool-kit/mocha":
    testDir: './mocha_tests'

lifecycles:
  "test:local":
    - "mocha"
    - "eslint"
  "test:ci": 
    - 'mocha'
    - "eslint"
  "@dotcom-tool-kit/n-test":
    host: "https://example.com"
