plugins:
  - '@dotcom-tool-kit/frontend-app'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/mocha'
  - '@dotcom-tool-kit/n-test'
  # - '@dotcom-tool-kit/upload-assets-to-s3'
  - '@dotcom-tool-kit/npm'
  - '@dotcom-tool-kit/circleci-heroku'

options:
  '@dotcom-tool-kit/eslint':
    files:
      - webpack.config.js
  '@dotcom-tool-kit/mocha':
    testDir: './mocha_tests'
  '@dotcom-tool-kit/n-test':
    host: 'https://example.com'

hooks:
  'test:local':
    - Mocha
    - Eslint
  'test:ci':
    - Mocha
    - Eslint
